waitingtime = {"Alabama": 48,
"Alaska": 0,
"Arizona": 24,
"Arkansas": 48,
"California": 0,
"Colorado": 0,
"Connecticut": 0,
"Delaware": 0,
"District of Columbia": 0,
"Florida": 24,
"Georgia": 24,
"Hawaii": 0,
"Idaho": 24,
"Illinois": 0,
"Indiana": 18,
"Iowa": 0,
"Kansas": 24,
"Kentucky": 24,
"Louisiana": 24,
"Maine": 0,
"Maryland": 0,
"Massachusetts": 0,
"Michigan": 24,
"Minnesota": 24,
"Mississippi": 24,
"Missouri": 72,
"Montana": 0,
"Nebraska": 24,
"Nevada": 0,
"New Hampshire": 0,
"New Jersey": 0,
"New Mexico": 0,
"New York": 0,
"North Carolina": 72,
"North Dakota": 24,
"Ohio": 24,
"Oklahoma": 72,
"Oregon": 0,
"Pennsylvania": 24,
"Rhode Island": 0,
"South Carolina": 24,
"South Dakota": 72,
"Tennessee": 48,
"Texas": 24,
"Utah": 72,
"Vermont": 0,
"Virginia": 24,
"Washington": 0,
"West Virginia": 24,
"Wisconsin": 24,
"Wyoming": 0 }

abbrevs = {"AL":"Alabama",
"AK":"Alaska",
"AZ":"Arizona",
"AR":"Arkansas",
"CA":"California",
"CO":"Colorado",
"CT":"Connecticut",
"DE":"Delaware",
"DC":"District of Columbia",
"FL":"Florida",
"GA":"Georgia",
"HI":"Hawaii",
"ID":"Idaho",
"IL":"Illinois",
"IN":"Indiana",
"IA":"Iowa",
"KS":"Kansas",
"KY":"Kentucky",
"LA":"Louisiana",
"ME":"Maine",
"MD":"Maryland",
"MA":"Massachusetts",
"MI":"Michigan",
"MN":"Minnesota",
"MS":"Mississippi",
"MO":"Missouri",
"MT":"Montana",
"NE":"Nebraska",
"NV":"Nevada",
"NH":"New Hampshire",
"NJ":"New Jersey",
"NM":"New Mexico",
"NY":"New York",
"NC":"North Carolina",
"ND":"North Dakota",
"OH":"Ohio",
"OK":"Oklahoma",
"OR":"Oregon",
"PA":"Pennsylvania",
"RI":"Rhode Island",
"SC":"South Carolina",
"SD":"South Dakota",
"TN":"Tennessee",
"TX":"Texas",
"UT":"Utah",
"VT":"Vermont",
"VA":"Virginia",
"WA":"Washington",
"WV":"West Virginia",
"WI":"Wisconsin",
"WY":"Wyoming" }
