# source http://www.guttmacher.org/statecenter/spibs/spib_MWPA.pdf
waitingtime = {"Alabama": 0,
"Alaska": 0,
"Arizona": 24,
"Arkansas": 48,
"California": 0,
"Colorado": 0,
"Connecticut": 0,
"Delaware": 0,
"District of Columbia": 0,
"Florida": 24,
"Georgia": 0,
"Hawaii": 0,
"Idaho": 0,
"Illinois": 0,
"Indiana": 18,
"Iowa": 0,
"Kansas": 0,
"Kentucky": 24,
"Louisiana": 24,
"Maine": 0,
"Maryland": 0,
"Massachusetts": 0,
"Michigan": 0,
"Minnesota": 0,
"Mississippi": 24,
"Missouri": 72,
"Montana": 0,
"Nebraska": 0,
"Nevada": 0,
"New Hampshire": 0,
"New Jersey": 0,
"New Mexico": 0,
"New York": 0,
"North Carolina": 0,
"North Dakota": 0,
"Ohio": 24,
"Oklahoma": 0,
"Oregon": 0,
"Pennsylvania": 0,
"Rhode Island": 0,
"South Carolina": 0,
"South Dakota": 72,
"Tennessee": 48,
"Texas": 24,
"Utah": 72,
"Vermont": 0,
"Virginia": 24,
"Washington": 0,
"West Virginia": 0,
"Wisconsin": 24,
"Wyoming": 0 }

# source http://thinkprogress.org/health/2015/02/25/3622531/cost-abortion-investigation/
# lack of data filled in 470
minabcost = {"Alabama": 440,
"Alaska": 650,
"Arizona": 440,
"Arkansas": 575,
"California": 512,
"Colorado": 515,
"Connecticut": 732,
"Delaware": 470,
"District of Columbia": 470,
"Florida": 495,
"Georgia": 400,
"Hawaii": 845,
"Idaho": 650,
"Illinois": 400,
"Indiana": 500,
"Iowa": 700,
"Kansas": 700,
"Kentucky": 600,
"Louisiana": 475,
"Maine": 550,
"Maryland": 375,
"Massachusetts": 650,
"Michigan": 485,
"Minnesota": 906,
"Mississippi": 530,
"Missouri": 545,
"Montana": 664,
"Nebraska": 660,
"Nevada": 485,
"New Hampshire": 550,
"New Jersey": 499,
"New Mexico": 450,
"New York": 525,
"North Carolina": 375,
"North Dakota": 575,
"Ohio": 440,
"Oklahoma": 575,
"Oregon": 550,
"Pennsylvania": 450,
"Rhode Island": 526,
"South Carolina": 523,
"South Dakota": 625,
"Tennessee": 625,
"Texas": 600,
"Utah": 450,
"Vermont": 550,
"Virginia": 475,
"Washington": 650,
"West Virginia": 450,
"Wisconsin": 500,
"Wyoming": 650 }

abbrevs = {"AL":"Alabama",
"AK":"Alaska",
"AZ":"Arizona",
"AR":"Arkansas",
"CA":"California",
"CO":"Colorado",
"CT":"Connecticut",
"DE":"Delaware",
"DC":"District of Columbia",
"FL":"Florida",
"GA":"Georgia",
"HI":"Hawaii",
"ID":"Idaho",
"IL":"Illinois",
"IN":"Indiana",
"IA":"Iowa",
"KS":"Kansas",
"KY":"Kentucky",
"LA":"Louisiana",
"ME":"Maine",
"MD":"Maryland",
"MA":"Massachusetts",
"MI":"Michigan",
"MN":"Minnesota",
"MS":"Mississippi",
"MO":"Missouri",
"MT":"Montana",
"NE":"Nebraska",
"NV":"Nevada",
"NH":"New Hampshire",
"NJ":"New Jersey",
"NM":"New Mexico",
"NY":"New York",
"NC":"North Carolina",
"ND":"North Dakota",
"OH":"Ohio",
"OK":"Oklahoma",
"OR":"Oregon",
"PA":"Pennsylvania",
"RI":"Rhode Island",
"SC":"South Carolina",
"SD":"South Dakota",
"TN":"Tennessee",
"TX":"Texas",
"UT":"Utah",
"VT":"Vermont",
"VA":"Virginia",
"WA":"Washington",
"WV":"West Virginia",
"WI":"Wisconsin",
"WY":"Wyoming" }
